import { Day } from "../interfaces";
export declare const chunk: (arr: any[], chunkSize: number) => [][];
export declare const getCurrentMonthAsString: (date: Date) => string;
export declare const getCurrentYearAsString: (date: Date) => string;
export declare const generatePreviousMonthDays: (firstDayOfMonthInWeek: number, currentDate: Date) => Day[];
export declare const generateNextMonthDays: (lastDayOfMonthInWeek: number, currentDate: Date) => Day[];
export declare const generateCurrentMonthDays: (daysInMonth: number, currentDate: Date) => Day[];
export declare const checkIsWeekend: (date: string) => boolean;
export declare const checkIsSameMonth: (date: string, currentDate: string) => boolean;
export declare const checkCanSelectDate: (date: string, currentDate: string, disableWeekendSelection?: boolean) => boolean;
